apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: secure-app
type: Opaque
data:
  API_TOKEN: c2tfbGl2ZV9hcGk=
  JWT_SECRET: cHJvZF9qd3Rfc2VjcmV0
  DB_USERNAME: c2VjdXJlX3VzZXI=
  DB_PASSWORD: U3Ryb25nUGFzc0AxMjM=
