apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: secure-app
data:
  APP_ENV: "production"
  APP_PORT: "5000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "secureapp"
